[project]
name = "mcp-server-airbnb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.4.0",
    "mcp>=1.0.0",
    "lxml>=5.0.0",
    "pydantic>=2.0.0",
]
